# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"\xab\x01\n\rProductObject\x12\n\n\x02id\x18\x01 \x01(\x04\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12+\n\x05state\x18\x05 \x01(\x0e\x32\x1c.product.ProductObject.State\".\n\x05State\x12\x0c\n\x08IN_ROUTE\x10\x00\x12\n\n\x06\x41\x43TIVE\x10\x02\x12\x0b\n\x07\x44ISABLE\x10\x03\"\x14\n\x12ProductListRequest\"?\n\x13ProductListResponse\x12(\n\x08products\x18\x01 \x03(\x0b\x32\x16.product.ProductObject\"*\n\x14\x44\x65leteProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x04\"(\n\x15\x44\x65leteProductResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"(\n\x12ReadProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x04\"O\n\x13ReadProductResponse\x12,\n\x07product\x18\x01 \x01(\x0b\x32\x16.product.ProductObjectH\x00\x88\x01\x01\x42\n\n\x08_product\"N\n\x12\x41\x64\x64ProductResponse\x12,\n\x07product\x18\x01 \x01(\x0b\x32\x16.product.ProductObjectH\x00\x88\x01\x01\x42\n\n\x08_product\"=\n\x12\x45\x64itProductRequest\x12\'\n\x07product\x18\x01 \x01(\x0b\x32\x16.product.ProductObject\">\n\x13\x45\x64itProductResponse\x12\'\n\x07product\x18\x01 \x01(\x0b\x32\x16.product.ProductObject2\xd7\x02\n\x07Product\x12\x41\n\x04List\x12\x1b.product.ProductListRequest\x1a\x1c.product.ProductListResponse\x12:\n\x03\x41\x64\x64\x12\x16.product.ProductObject\x1a\x1b.product.AddProductResponse\x12\x41\n\x04\x45\x64it\x12\x1b.product.EditProductRequest\x1a\x1c.product.EditProductResponse\x12G\n\x06\x44\x65lete\x12\x1d.product.DeleteProductRequest\x1a\x1e.product.DeleteProductResponse\x12\x41\n\x04Read\x12\x1b.product.ReadProductRequest\x1a\x1c.product.ReadProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRODUCTOBJECT']._serialized_start=27
  _globals['_PRODUCTOBJECT']._serialized_end=198
  _globals['_PRODUCTOBJECT_STATE']._serialized_start=152
  _globals['_PRODUCTOBJECT_STATE']._serialized_end=198
  _globals['_PRODUCTLISTREQUEST']._serialized_start=200
  _globals['_PRODUCTLISTREQUEST']._serialized_end=220
  _globals['_PRODUCTLISTRESPONSE']._serialized_start=222
  _globals['_PRODUCTLISTRESPONSE']._serialized_end=285
  _globals['_DELETEPRODUCTREQUEST']._serialized_start=287
  _globals['_DELETEPRODUCTREQUEST']._serialized_end=329
  _globals['_DELETEPRODUCTRESPONSE']._serialized_start=331
  _globals['_DELETEPRODUCTRESPONSE']._serialized_end=371
  _globals['_READPRODUCTREQUEST']._serialized_start=373
  _globals['_READPRODUCTREQUEST']._serialized_end=413
  _globals['_READPRODUCTRESPONSE']._serialized_start=415
  _globals['_READPRODUCTRESPONSE']._serialized_end=494
  _globals['_ADDPRODUCTRESPONSE']._serialized_start=496
  _globals['_ADDPRODUCTRESPONSE']._serialized_end=574
  _globals['_EDITPRODUCTREQUEST']._serialized_start=576
  _globals['_EDITPRODUCTREQUEST']._serialized_end=637
  _globals['_EDITPRODUCTRESPONSE']._serialized_start=639
  _globals['_EDITPRODUCTRESPONSE']._serialized_end=701
  _globals['_PRODUCT']._serialized_start=704
  _globals['_PRODUCT']._serialized_end=1047
# @@protoc_insertion_point(module_scope)
