DEFINED_DIR_OF_SERVICE = "./.gutils/Service"

STANDART_DIR_OF_SERVICES = 'gServices'
STANDART_COMPOSE_FILE = 'local.yaml'
STANDART_EXECUTABLE_FILE = 'server.py'
STANDART_MAKEFILE = "Makefile"
STANDART_DATABASE_CONNECTION = "piccolo_conf.py"
STANDART_REQUIREMENTS_FILE = "requirements.txt"
STANDART_DOCKER_FILE = "Dockerfile"

STANDART_EXECFILE_GATEWAY = "main.py"