# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty_test
    ports:
      - "5432:5432"


  product_service:
    container_name: product_microservice
    build:
      context: ./Product/
      dockerfile: ./Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      - db

  basket_service:
    container_name: basket_microservice
    build:
      context: ./Basket/
      dockerfile: ./Dockerfile
    ports:
      - "50052:50052"
    depends_on:
      - db

  user_service:
    container_name: user_microservice
    build:
      context: ./User/
      dockerfile: ./Dockerfile
    ports:
      - "50053:50053"
    depends_on:
      - db

  
  jeager_service:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14269:14269"
      - "9411:9411"
    depends_on:
      - product_service
      - basket_service

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
